import chalk from 'chalk';

const WIDTH = 62;

function box(lines) {
  const top = '╔' + '═'.repeat(WIDTH) + '╗';
  const bottom = '╚' + '═'.repeat(WIDTH) + '╝';
  const body = lines.map((l) => {
    const padded = l.padEnd(WIDTH, ' ');
    return '║' + padded + '║';
  });
  return [top, ...body, bottom].join('\n');
}

function divider(label) {
  const dashes = '━'.repeat(Math.max(0, WIDTH - label.length - 2));
  return chalk.dim(`━━━ ${label} ${dashes}`);
}

function renderMarkdown(text, color) {
  return text
    .split('\n')
    .map((line) => {
      // Headers
      if (line.startsWith('### ')) return color.bold(line.replace(/^### /, '  '));
      if (line.startsWith('## ')) return color.bold(line.replace(/^## /, ''));
      if (line.startsWith('# ')) return color.bold.underline(line.replace(/^# /, ''));
      // Bullet points
      if (line.startsWith('- ') || line.startsWith('* ')) {
        return color('  ' + line.replace(/^[-*] /, '• '));
      }
      // Numbered list
      if (/^\d+\. /.test(line)) {
        return color('  ' + line);
      }
      // Bold inline
      return color(line.replace(/\*\*(.+?)\*\*/g, (_, m) => chalk.bold(m)));
    })
    .join('\n');
}

export function printHeader(question) {
  const q = question.length > WIDTH - 4 ? question.slice(0, WIDTH - 7) + '...' : question;
  const titleLine = '  ⚔️  CLAUDE VS CLAUDE  ⚔️'.padEnd(WIDTH, ' ');
  const qLine = `  "${q}"`.padEnd(WIDTH, ' ');
  const spacer = ''.padEnd(WIDTH, ' ');
  console.log('\n' + chalk.magenta(box([spacer, titleLine, spacer, qLine, spacer])));
}

export function printAdvocateA(text, round) {
  const label = round > 1 ? `ADVOCATE A — Round ${round}` : 'ADVOCATE A';
  console.log('\n' + divider(label));
  console.log(renderMarkdown(text, chalk.cyan));
}

export function printAdvocateB(text, round) {
  const label = round > 1 ? `ADVOCATE B — Round ${round}` : 'ADVOCATE B';
  console.log('\n' + divider(label));
  console.log(renderMarkdown(text, chalk.yellow));
}

export function printJudge(text) {
  console.log('\n' + divider('THE VERDICT'));
  console.log(renderMarkdown(text, chalk.green));
  console.log('\n' + chalk.dim('━'.repeat(WIDTH)));
}

export function printRoundBadge(round, total) {
  console.log('\n' + chalk.magenta.bold(`  ◆ Round ${round} of ${total}`));
}

export function formatMarkdownDoc(question, rounds, judgment) {
  const debateBlocks = rounds
    .map((r, i) => {
      const roundNum = i + 1;
      return `## Round ${roundNum}\n\n### Advocate A\n\n${r.advocateA}\n\n### Advocate B\n\n${r.advocateB}`;
    })
    .join('\n\n---\n\n');

  return `# Architecture Decision: ${question}

> Generated by [claude-vs-claude](https://github.com/NickCirv/claude-vs-claude)
> Date: ${new Date().toISOString().split('T')[0]}

---

## The Debate

${debateBlocks}

---

## The Verdict

${judgment}

---

*Generated with claude-vs-claude — Two AIs debate. You decide.*
`;
}
